apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hnyc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-hnyc@sha256:2e6b30dc40963cb274acafe3ad7daae1fb80314454501165a046b1186f0ee88c
        name: my-nodejs
        resources: {}
status: {}
